console.log("6. Determinar numero A y B, sumarlos si al menos uno de ellos es negativo, en caso contrario multiplicarlos")
console.log("ingrese el numero A");
let numero1 = 9;
console.log(numero1)
console.log("ingrese el NUMERO B");
let numero2 = 7;
console.log(numero2)
if (numero1, numero2 < 0 ) {
    console.log ("uno de los numeros es negativo, la suma es: ");
    let suma = (numero1+numero2);
    console.log (suma)
} else (numero1,numero2 > 0);{
    console.log ("la division fue posible realizar");
    let (numero1/numero2)
    console.log("Division");}